### ISSUE TITLE
TransformPushFiltersIntoBGP drops FILTER even when it cannot be applied to BGP

### ISSUE THREAD

**Issue by jindrichmynarz** [SmartDataAnalytics/jena-sparql-api#12]
TransformPushFiltersIntoBGP drops `FILTER` conditions even when they cannot be applied to BGP. For example:

```sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT *
WHERE {
  ?a a skos:Concept .
  ?b a skos:Concept .
  FILTER (?a != ?b)
}
```

Ends up as this:

```sparql
SELECT  *
WHERE
  { ?a  a                     <http://www.w3.org/2004/02/skos/core#Concept> .
    ?b  a                     <http://www.w3.org/2004/02/skos/core#Concept>
  }
```

Tested with the 3.1.1-1-SNAPSHOT.

**Comment by Aklakan** [comment]
The source of the problem was, that the transformer would find equality clauses (?x = c) or (c = ?x) and push these constraints into the BGP, but it would forget to any residual clauses as filters.

The transformer has been improved to correctly keep to track of and properly apply the filter clauses. But needs more testing. Right now there is an issues with round tripping TransformReplaceConstants (turns all constants in triple patterns into filters) and TransformPushFiltersIntoBGP (where applicable, turns all filters into constants of triple patterns) because of an introduced projection which does not get optimized away.

**Comment by Aklakan** [comment]
Issue should be fixed, and the test case suite has been updated. More test cases greatly welcome :)
